
exports.seed = function(knex, Promise) {
  return knex.raw('DELETE FROM "camp"; ALTER SEQUENCE camp_id_seq RESTART WITH 24;')
    .then(function () {
      var camps = [{
        id: 1,
        organization_name: '3D Lacrosse',
        program_name: 'Colorado Boys Small Group Training',
        program_address: '1301 S. Jason Street Unit K',
        program_city: 'Denver',
        program_state: 'CO',
        zipcode: 80223,
        program_phone: '(800)941-9193',
        program_website: 'https://3dlacrosse.com',
        program_type: 'Sports',
        program_description: 'Small Group Training is position focused and will be capped at a maximum of ten participants per session to ensure personal attention and development. The practice plans in Small Group Training allow your player a high intensity workout with maximum repetition and creative drills that will help keep training fresh and challenging. Small Group Training is open to players of all skill levels and positions! Small Group Training will consist of four sessions, each which will have four, one hour training blocks for a total of four hours per session.',
        participant_gender: 'Male',
        participant_age_min: 8,
        participant_age_max: 18,
        program_start_date: '2018-01-03',
        program_end_date: '2018-02-22',
        program_start_time: '5:00PM',
        program_end_time: '7:00PM',
        overnight: 'False',
        full_day: 'False',
        part_day: 'True',
        cost: 175
      }, {
        id: 2,
        organization_name: '3D Lacrosse',
        program_name: 'Colorado Girls Small Group Training',
        program_address: '1301 S. Jason Street Unit K',
        program_city: 'Denver',
        program_state: 'CO',
        zipcode: 80223,
        program_phone: '(800)941-9193',
        program_website: 'https://3dlacrosse.com',
        program_type: 'Sports',
        program_description: 'Small Group Training is position-focused and will be capped at a maximum of ten participants per session to ensure personal attention and development. Our coaches will deliver a high-intensity workout with maximum repetitions and fast-paced drills that will help keep training fresh and challenging. Small Group Training is open to players of all skill levels and positions! Small Group Training will consist of four sessions, each of which will have four, one hour training blocks for a total of four hours per session. All training will take place at the 3d Lacrosse Office - address listed below. *Please note that if we have more than 10 registrations per group, we will form an additional group*',
        participant_gender: 'Female',
        participant_age_min: 8,
        participant_age_max: 18,
        program_start_date: '2018-01-06',
        program_end_date: '2018-03-02',
        program_start_time: '5:00PM',
        program_end_time: '7:00PM',
        overnight: 'False',
        full_day: 'False',
        part_day: 'True',
        cost:100
      }, {
        id: 3,
        organization_name: '3D Lacrosse',
        program_name: 'Colorado Spring Little Laxers',
        program_address: '1301 S. Jason Street Unit K',
        program_city: 'Denver',
        program_state: 'CO',
        zipcode: 80223,
        program_phone: '(800)941-9193',
        program_website: 'https://3dlacrosse.com',
        program_type: 'Sports',
        program_description: 'At 3d Lacrosse we are dedicated to a better lacrosse experience, from our most tenured players down to our youngest beginners. Our Little Laxers program is designed to foster and create a love of the game by increasing skill and IQ. Players will be introduced to the basics of lacrosse through proper repetition and fun games that reinforce their new abilities. Each session will review and build upon the fundamentals of the previous weeks training through the Box-Field Hybrid™ Development System. Players will learn the terminology of different concepts and a repertoire of passes, fakes, shots, and dodges that will create confidence and passion. This program is open to boys and girls. Small-sided games will take place at the end of each session, allowing the players to showcase their new skills and knowledge, and at the same time, developing a greater understanding of the game.',
        participant_gender: 'Any',
        participant_age_min: 6,
        participant_age_max: 9,
        program_start_date: '2018-01-06',
        program_end_date: '2018-04-27',
        program_start_time: '6:00PM',
        program_end_time: '7:15PM',
        overnight: 'False',
        full_day: 'True',
        part_day: 'False',
        cost: 100
      }, {
        id: 4,
        organization_name: '4 Corners Christian Camp',
        program_name: 'Summer Camp',
        program_address: '14051 CR 37',
        program_city: 'Mancos',
        program_state: 'CO',
        zipcode: 81328,
        program_phone: '(970)882-2523',
        program_website: 'http://www.fcccamp.org/student-camps.html',
        program_type: 'Faith-Based',
        program_description: 'All of our camps are designed to be unique Christian camping experiences that each camper will enjoy and that will lead students to a deeper faith in Christ.   At each of our camps you will experience relevant Bible reaching, powerful worship times, delicious food, fun games and activities, awesome Rocky Mountain hiking, comfortable accommodations and a western Colorado view that is second to none.',
        participant_gender: 'Any',
        participant_age_min: 12,
        participant_age_max: 18,
        program_start_date: '2018-06-04',
        program_end_date: '2018-06-09',
        program_start_time: '8:00AM',
        program_end_time: '6:00PM',
        overnight: 'True',
        full_day: 'True',
        part_day: 'False',
        cost: 260
      }, {
        id: 5,
        organization_name: '5280 Gymnastics',
        program_name: 'Spring Break Day Camp',
        program_address: '10601 W 44th Ave',
        program_city: 'Wheat Ridge',
        program_state: 'CO',
        zipcode: 80033,
        program_phone: '(303)431-8838',
        program_website: 'http://5280gymnastics.com/5280/camps/',
        program_type: 'Sports',
        program_description: 'Hi parents! Welcome to 5280’s Spring Break Day Camp. Our camp provides children with a safe environment to experience gymnastics, athletic games, arts and crafts, music, and plenty of fun. Our qualified coaches and staff are committed to giving your child an exciting and rewarding camp experience. Space is limited, so please sign-up in the office as soon as possible! DAY CAMP – IN A NUTSHELL…',
        participant_gender: 'Any',
        participant_age_min: 5,
        participant_age_max: 18,
        program_start_date: '2018-03-31',
        program_end_date: '2018-03-27',
        program_start_time: '7:30AM',
        program_end_time: '5:30PM',
        overnight: 'False',
        full_day: 'True',
        part_day: 'False',
        cost: 300
      }, {
        id: 6,
        organization_name: '5280 Gymnastics',
        program_name: 'Summer Break Day Camp',
        program_address: '10601 W 44th Ave',
        program_city: 'Wheat Ridge',
        program_state: 'CO',
        zipcode: 80033,
        program_phone: '(303)431-8838',
        program_website: 'http://5280gymnastics.com/5280/camps/',
        program_type: 'Sports',
        program_description: 'Hi parents! Welcome to 5280’s Summer Break Day Camp. Our camp provides children with a safe environment to experience gymnastics, athletic games, arts and crafts, music, and plenty of fun. Our qualified coaches and staff are committed to giving your child an exciting and rewarding camp experience. Space is limited, so please sign-up in the office as soon as possible! DAY CAMP – IN A NUTSHELL…',
        participant_gender: 'Any',
        participant_age_min: 5,
        participant_age_max: 18,
        program_start_date: '2018-07-24',
        program_end_date: '2018-08-11',
        program_start_time: '7:30AM',
        program_end_time: '5:30PM',
        overnight: 'False',
        full_day: 'True',
        part_day: 'False',
        cost: 300
      }, {
        id: 7,
        organization_name: 'A+ Athletics',
        program_name: 'Summer Camp',
        program_address: '7104 S. Dillon Ct.',
        program_city: 'Centennial',
        program_state: 'CO',
        zipcode: 80112,
        program_phone: '(303)953-7320',
        program_website: 'https://www.aplusathletics.com/camps/summer-camp/',
        program_type: 'General',
        program_description: 'At A+ Plus Athletics, campers feel good about themselves as our non-competitive curriculum enhances the spirit of “I AM A CHAMPION” in each child. While learning gymnastics, our unique program focuses on the PROCESS…where kids’ gymnastic skills are enhanced while maximizing fun! Our staff teaches with care using goal setting, progressions, and positive encouragement. This gymnastics camp is designed for boys and girls who are eager for fun via exciting, engaging activities! Children learn gymnastics skills on a variety of applications, including vault, bars, balance beam, trampoline and the floor. Extra time is provided to give young gymnasts the opportunity to work on the activity of their choice! TEAM SPIRIT is encouraged as we incorporate exciting themes into our daily activities. Themes will be used to incorporate age–appropriate games, arts & crafts, sports and agility. Our gymnastics camp features a low student to teacher ratio, making this time the perfect opportunity for young campers to have a grand time while the more experienced children can enhance their gymnastics training!',
        participant_gender: 'Any',
        participant_age_min: 4,
        participant_age_max: 17,
        program_start_date: '2018-05-29',
        program_end_date: '2018-08-11',
        program_start_time: '9:00AM',
        program_end_time: '4:30PM',
        overnight: 'False',
        full_day: 'True',
        part_day: 'False',
        cost: 275
      }, {
        id: 8,
        organization_name: 'ABC Kids Climbing',
        program_name: 'Indoor Summer Camps',
        program_address: '1960 32nd St',
        program_city: 'Boulder',
        program_state: 'CO',
        zipcode: 80301,
        program_phone: '(303)443-5437',
        program_website: 'http://www.abckidsboulder.com/camps/',
        program_type: 'Sports',
        program_description: 'Three or five days, full or half days options. Climbers will build the confidence to defy gravity in this inspiring week of fun and challenge. The kids will learn new tricks and techniques to tackle hurdles with fluidity and control. Games and activities will focus on body awareness, balance, and footwork. Climbers will get to work together as a team, laugh and leap their way through obstacle course, and experience everything else that makes our camps great.',
        participant_gender: 'Any',
        participant_age_min: 5,
        participant_age_max: 14,
        program_start_date: '2018-07-24',
        program_end_date: '2018-08-18',
        program_start_time: '9:00AM',
        program_end_time: '3:30PM',
        overnight: 'False',
        full_day: 'True',
        part_day: 'True',
        cost: 395
      }, {
        id: 9,
        organization_name: 'Abrakadoodle',
        program_name: 'The World is My Canvas Art Camp',
        program_address: '2450 S Wabash St',
        program_city: 'Denver',
        program_state: 'CO',
        zipcode: 80231,
        program_phone: 'info@abrakadoodle.com',
        program_website: 'http://www.abrakadoodle.com/co-north-and-west-denver/',
        program_type: 'Arts',
        program_description: 'Abrakadoodle Art Camps inspire kids to reach beyond and create art that is unique to them. By doing so, kids feel empowered to be creative and expressive. It’s amazing to see just what kids design when given the freedom to explore and to express themselves creatively! Imaginations soar! Each Art Camp for Kids Includes: Art lessons, Games, Stories, Music, Activities, And tons of smiles, laughs and FUN!',
        participant_gender: 'Any',
        participant_age_min: 4,
        participant_age_max: 12,
        program_start_date: '2018-07-17',
        program_end_date: '2018-07-21',
        program_start_time: '9:00AM',
        program_end_time: '4:00PM',
        overnight: 'False',
        full_day: 'True',
        part_day: 'True',
        cost: 185
      }, {
        id: 10,
        organization_name: "Academy of Children's Theater Camps",
        program_name: 'Musical Theatre',
        program_address: '2314 Vickers Drive',
        program_city: 'Colorado Springs',
        program_state: 'CO',
        zipcode: 80918,
        program_phone: 'director@ACTcolorado.net',
        program_website: 'https://actcolorado.net/camps/',
        program_type: 'Arts',
        program_description: 'Students attending this fun-filled camp will enjoy exploring the aspects of theatre, including fun theatre games, dressing up in costumes, learning musical theatre skills, along with preparing and performing  on a REAL STAGE at the last day of camp!',
        participant_gender: 'Any',
        participant_age_min: 4,
        participant_age_max: 18,
        program_start_date: '2018-06-05',
        program_end_date: '2018-07-28',
        program_start_time: '9:00AM',
        program_end_time: '3:00PM',
        overnight: 'False',
        full_day: 'True',
        part_day: 'False',
        cost: 235
      }, {
        id: 11,
        organization_name: 'Active Learning',
        program_name: '3D Concepts',
        program_address: '4545 S. University Blvd',
        program_city: 'Englewood',
        program_state: 'CO',
        zipcode: 80110,
        program_phone: '(888)652-4377',
        program_website: 'https://www.activelearningcamps.com/',
        program_type: 'Education',
        program_description: 'Computer enrichment programs typically have two longer sessions with a snack break in between. At the beginning of camp they will be assigned a computer and will work on that machine throughout the week. The instructor will follow our step by step curriculum as the kids learn to create their games or projects. Then for the final days of the camps, they are given time to create on their own, building multiple levels adding characters and making their game just the way they want it. All day campers follow the same schedule, with an hour-long lunch/recess break between the morning and afternoon sessions. Since the computer classes are half day courses, students will many times change rooms after the break and begin to learn a new game or software program in the afternoon.',
        participant_gender: 'Any',
        participant_age_min: 5,
        participant_age_max: 15,
        program_start_date: '2018-07-10',
        program_end_date: '2018-07-14',
        program_start_time: '9:00AM',
        program_end_time: '4:00PM',
        overnight: 'False',
        full_day: 'True',
        part_day: 'True',
        cost: 315
      }, {
        id: 12,
        organization_name: 'Active Learning',
        program_name: 'All Day Chess',
        program_address: '4820 Nautilius Court North',
        program_city: 'Boulder',
        program_state: 'CO',
        zipcode: 80301,
        program_phone: '(888)652-4377',
        program_website: 'https://www.activelearningcamps.com/',
        program_type: 'Education',
        program_description: "The camp schedule is structured, but at the same time it is fun. Classroom size for our chess program averages 12-15 campers.  We make every effort to group friends together, but groupings within the chess programs are dependent on the camper's chess playing ability. Teaching methods and lessons are specific to each instructor, but the main focus is the same: present the chess material in a fun, exhilarating and entertaining way. All necessary equipment is provided. There are no expectations placed upon the campers, and the atmosphere is very relaxed. A typical day in our chess program will include instruction, activities and, of course, an opportunity to try their new skills with an opponent. For half day campers, the day consists of two classroom lessons lasting an hour each, with an hour break in between for practice and snack. All-day campers follow the same schedule in the afternoon: an hour lesson with an hour break in between for practice and snack and then a final lesson.",
        participant_gender: 'Any',
        participant_age_min: 5,
        participant_age_max: 15,
        program_start_date: '2018-06-26',
        program_end_date: '2018-07-14',
        program_start_time: '9:00AM',
        program_end_time: '4:00PM',
        overnight: 'False',
        full_day: 'True',
        part_day: 'False',
        cost: 445
      }, {
        id: 13,
        organization_name: 'Active Learning',
        program_name: 'Video Game Creation-Platform Style',
        program_address: '21 Broadmoor Avenue',
        program_city: 'Colorado Springs',
        program_state: 'CO',
        zipcode: 80906,
        program_phone: '(888)652-4377',
        program_website: 'https://www.activelearningcamps.com/',
        program_type: 'Education',
        program_description: 'Computer enrichment programs typically have two longer sessions with a snack break in between. At the beginning of camp they will be assigned a computer and will work on that machine throughout the week. The instructor will follow our step by step curriculum as the kids learn to create their games or projects. Then for the final days of the camps, they are given time to create on their own, building multiple levels adding characters and making their game just the way they want it. All day campers follow the same schedule, with an hour-long lunch/recess break between the morning and afternoon sessions.  Since the computer classes are half day courses, students will many times change rooms after the break and begin to learn a new game or software program in the afternoon.',
        participant_gender: 'Any',
        participant_age_min: 5,
        participant_age_max: 15,
        program_start_date: '2018-06-19',
        program_end_date: '2018-06-23',
        program_start_time: '9:00AM',
        program_end_time: '4:00PM',
        overnight: 'False',
        full_day: 'False',
        part_day: 'True',
        cost: 340
      }, {
        id: 14,
        organization_name: 'Adams Camp',
        program_name: 'Adventure Camp',
        program_address: '1101 County Road 53',
        program_city: 'Granby',
        program_state: 'CO',
        zipcode: 80446,
        program_phone: '(303)563-8290',
        program_website: 'https://adamscampcolorado.org/adventure-camps/#adventure-camp-dates',
        program_type: 'Outdoors',
        program_description: 'Adventure Camp is a 5 day/night sleep away-camp that is full of fun, challenge and adventure! Campers enjoy activities that expand social horizons and provide the opportunity to develop the courage to try new things while increasing independence and confidence.',
        participant_gender: 'Any',
        participant_age_min: 9,
        participant_age_max: 18,
        program_start_date: '2018-07-17',
        program_end_date: '2018-08-03',
        program_start_time: '8:00AM',
        program_end_time: '6:00PM',
        overnight: 'True',
        full_day: 'True',
        part_day: 'False',
        cost: 950
      }, {
        id: 15,
        organization_name: 'Adams Camp',
        program_name: 'Therapy Camp',
        program_address: '1101 County Road 53',
        program_city: 'Granby',
        program_state: 'CO',
        zipcode: 80446,
        program_phone: '(303)563-8290',
        program_website: 'https://adamscampcolorado.org/adventure-camps/#adventure-camp-dates',
        program_type: 'Outdoors',
        program_description: 'Early Start is a half-day intensive therapy program appropriate for children age 4 and under. Locations vary. Early Start Highlights: 3 hours of daily one-on-one therapy for 5 consecutive days, Teams of 4 pediatric therapists including speech, physical, occupational and music therapists and 2 volunteers work with just 4 children, Parents are encouraged to observe and participate in order to learn therapeutic interventions',
        participant_gender: 'Any',
        participant_age_min: 1,
        participant_age_max: 4,
        program_start_date: '2018-03-26',
        program_end_date: '2018-03-31',
        program_start_time: '8:00AM',
        program_end_time: '6:00PM',
        overnight: 'True',
        full_day: 'True',
        part_day: 'False',
        cost: 1400
      }, {
        id: 16,
        organization_name: 'Adaptive Adventures',
        program_name: 'STARS OF TOMORROW YOUTH SPORTS CAMP',
        program_address: '1700 Sheridan Blvd',
        program_city: 'Denver',
        program_state: 'CO',
        zipcode: 80219,
        program_phone: '(303)679-2770',
        program_website: 'https://adaptiveadventures.org/event/stars-tomorrow-youth-sports-camp',
        program_type: 'Outdoors',
        program_description: "Join us in kicking off the summer with two awesome days at Denver's Sloan's Lake! STARS of Tomorrow Youth Sports Camp gives our youth with physical disabilities the opportunity to experience a variety of adaptive sports, including handcycling, rock climbing, water-skiing, kayaking, paddleboarding, field games, and much more! This camp will serve kids ages 5-18, who can participate for FREE! The camp also includes lunch, snacks, amazing people, and GREAT memories!",
        participant_gender: 'Any',
        participant_age_min: 5,
        participant_age_max: 18,
        program_start_date: '2018-06-29',
        program_end_date: '2018-06-30',
        program_start_time: '8:00AM',
        program_end_time: '3:00PM',
        overnight: 'False',
        full_day: 'True',
        part_day: 'False',
        cost: 0
      }, {
        id: 17,
        organization_name: 'Adidas Tennis Camps',
        program_name: 'Colorado State University Tennis Camps',
        program_address: 'Colorado State University',
        program_city: 'Fort Collins',
        program_state: 'CO',
        zipcode: 80523,
        program_phone: '(800)944-7112',
        program_website: 'http://tenniscamper.com/tennis-camp/colorado-state-university-tennis-camps/',
        program_type: 'Sports',
        program_description: "The Williams Tennis School and its coaches oversee, manage, and teach at the popular Adidas Tennis Camp, held annually on the Colorado State University campus in Ft. Collins, CO. These camps are run at select locations across the U.S. and Steve Williams (middle) with 2 of his assistant instructorswe are so fortunate to have a great sponsor and superior location to conduct an awesome tennis camp. This camp is open to any and all entrants. Tennis players of all ability levels will benefit from a week at this camp. Campers will be evaluated on the first day and placed in groups to maximize their potential. Each staff member is dedicated to the personal development and improvement of every tennis camper, from beginners to top tournament players. Steve Williams instructing future tennis prosThe Adidas Tournament Training Camps were developed to provide advanced junior players with an opportunity to become better tennis match players and improve their tournament results. Every tournament player in any age group will benefit from these intense camp sessions. Players will train with other motivated tournament  Adidas Tennis Campsplayers and compete against each other in a constructive, fun, and well-organized camp setting. This challenging atmosphere will provide a great opportunity for juniors to improve their USTA rankings. Don't miss out on top notch training at the best summer tennis camps in the country.",
        participant_gender: 'Any',
        participant_age_min: 8,
        participant_age_max: 17,
        program_start_date: '2018-06-11',
        program_end_date: '2018-06-30',
        program_start_time: '8:45AM',
        program_end_time: '4:00PM',
        overnight: 'True',
        full_day: 'True',
        part_day: 'False',
        cost: 855
      }, {
        id: 18,
        organization_name: 'Adventure Treks',
        program_name: 'Colorado Explorer',
        program_address: 'Denver International Airport',
        program_city: 'Denver',
        program_state: 'CO',
        zipcode: 80249,
        program_phone: '(888)954-5555',
        program_website: 'https://www.adventuretreks.com/teen-adventure-camp/colorado-explorer/',
        program_type: 'Outdoors',
        program_description: 'Spend two magical weeks exploring the diverse terrain of Colorful Colorado. In Rocky Mountain National Park, walk through fields laden with blue and purple wildflowers. Near Salida, become familiar with the alpine desert landscape while rock climbing and mountain biking with the massive 14,000-foot peaks of the Sawatch Range as your backdrop. Navigate the rapids in Brown’s Canyon on the Arkansas River, considered the best stretch of whitewater rafting in Colorado. Hike your way to unbeatable views on the 12,324-foot Flattop Mountain, and finish your trip with rafting on the Cache La Poudre River’s nonstop rollercoaster rapids!',
        participant_gender: 'Any',
        participant_age_min: 13,
        participant_age_max: 14,
        program_start_date: '2018-06-23',
        program_end_date: '2018-08-10',
        program_start_time: '8:00AM',
        program_end_time: '6:00PM',
        overnight: 'True',
        full_day: 'True',
        part_day: 'False',
        cost: 2995
      }, {
        id: 19,
        organization_name: 'AEI Base Camp',
        program_name: 'Hunting and Fishing Skills Camp',
        program_address: '2 Illinois Creek',
        program_city: 'Almont',
        program_state: 'CO',
        zipcode: 81210,
        program_phone: '(970)641-4708',
        program_website: 'http://www.aeibasecamp.com/open-enrollment-adventures/',
        program_type: 'Outdoors',
        program_description: 'Do you love outdoor adventure? Have you ever wanted to improve your technical outdoor skills or learn new ones? Join other adventurers as we teach participants valuable skills to gain confidence and competence in outdoor pursuits! Your teenager will learn these skills and techniques from a 30+ year veteran outfitter, AEI Guide and Outfitter. This Hunting and Fishing Skills Camp takes place in picturesque Taylor Park, Colorado. With towering 13,000+ peaks and the Continental Divide as your backdrop, this will be an epic experience that you will remember forever.',
        participant_gender: 'Any',
        participant_age_min: 13,
        participant_age_max: 18,
        program_start_date: '2018-06-15',
        program_end_date: '2018-06-24',
        program_start_time: '8:00AM',
        program_end_time: '6:00PM',
        overnight: 'True',
        full_day: 'False',
        part_day: 'False',
        cost: 695
      }, {
        id: 20,
        organization_name: 'Air Force Academy Sports Camps',
        program_name: 'Sports Camps',
        program_address: '2169 Field House Dr',
        program_city: 'USAFA',
        program_state: 'CO',
        zipcode: 80840,
        program_phone: '(719)333-2116',
        program_website: 'http://www.goairforcefalcons.com/camps/',
        program_type: 'Sports',
        program_description: 'This summer will once again be packed with great opportunities for athletes of all ages to hone their skills in their sport of choice. We will offer sports camps in the following sports: baseball, basketball, cheerleading, cross country, diving, fencing, football, golf, gymnastics, hockey, lacrosse, soccer, swimming, tennis, track and field, volleyball and wrestling. ',
        participant_gender: 'Any',
        participant_age_min: 5,
        participant_age_max: 18,
        program_start_date: '2018-06-12',
        program_end_date: '2018-06-28',
        program_start_time: '8:30AM',
        program_end_time: '4:30PM',
        overnight: 'True',
        full_day: 'True',
        part_day: 'True',
        cost: 700
      }, {
        id: 21,
        organization_name: 'Ajax Adventure Camp',
        program_name: 'AJAX Sleepaway Camp',
        program_address: 'Aspen Middle School',
        program_city: 'Aspen',
        program_state: 'CO',
        zipcode: 81611,
        program_phone: '(970)205-9392',
        program_website: 'http://ajaxadventurecamp.com',
        program_type: 'Outdoors',
        program_description: "Welcome to Ajax Adventure Ranch Camp! Nestled in the rocky mountains, surrounded by streams, lakes and mountain peaks, Ajax Adventure Ranch Camp's Tipi village is home to our adventurous sleepaway campers. Here on the ranch, kids will be given the choice of activities ranging from rock climbing, paddleboarding, archery, fishing, and cowboy paintball to rockets, crafts, survival skills, camping, and barnyard activities. We have 100's of other activities for campers to choose from throughout the summer. Campers will also help raise the ranch pigs, chickens, goats, and other farmyard animals. This will be a true adventure sleepaway camp where campers, can build new structures and camp traditions while shaping the future of Ajax Adventure Ranch Camp. For campers that like a rustic sleepaway environment with tons of activities, an ever-flowing fun atmosphere, and a true sleepaway experience in the high rockies, this is the place. If campers prefer a sleepaway camp with manicured lawns, maid service, and daily massages, we recommend somewhere in New York. We offer 8 different week-long sessions throughout the summer (each session begins on a Sunday and ends on a Saturday). Campers may attend up to 4 sessions. Dropoff and pickup is at the Aspen Middle school and we will transport campers to the ranch (1+ hr into the mountains from Aspen). We have one unique session this summer in partnership with the Aspen Center for Environmental Studies (the July 10th session); emphasizing wilderness survival skills, animal tracking, and other activities that the experts at ACES will help deliver.",
        participant_gender: 'Any',
        participant_age_min: 8,
        participant_age_max: 15,
        program_start_date: '2018-06-19',
        program_end_date: '2018-08-19',
        program_start_time: '8:00AM',
        program_end_time: '6:00PM',
        overnight: 'True',
        full_day: 'True',
        part_day: 'False',
        cost: 1100
      }, {
        id: 22,
        organization_name: 'Alpine Arts Center',
        program_name: 'Drawing, Cartooning & Caricatures',
        program_address: '280 Main Street C-101',
        program_city: 'Edwards',
        program_state: 'CO',
        zipcode: 81632,
        program_phone: '(970)926-2732',
        program_website: 'https://clients.mindbodyonline.com/ASP/main_enroll.asp?studioid=25709&tg=29&vt=&lvl=&stype=-101&view=day&trn=0&page=&catid=&prodid=&date=4%2f20%2f2017&classid=0&prodGroupId=&sSU=&optForwardingLink=&qParam=&justloggedin=&nLgIn=&pMode=0&loc=1',
        program_type: 'Arts',
        program_description: "Campers will explore drawing, cartooning, and caricature projects in a variety of mediums including painting, drawing, printmaking, and clay! We'll make self-portraits, learn how to break complex forms into simple shapes, and have fun creating imaginary characters and scenes.",
        participant_gender: 'Any',
        participant_age_min: 3,
        participant_age_max: 12,
        program_start_date: '2018-07-24',
        program_end_date: '2018-07-28',
        program_start_time: '9:00AM',
        program_end_time: '4:00PM',
        overnight: 'False',
        full_day: 'True',
        part_day: 'True',
        cost: 199
      }, {
        id: 23,
        organization_name: 'Alpine Arts Center',
        program_name: "Young Artists' Workshop",
        program_address: '280 Main Street C-101',
        program_city: 'Edwards',
        program_state: 'CO',
        zipcode: 81632,
        program_phone: '(970)926-2732',
        program_website: 'https://clients.mindbodyonline.com/ASP/main_enroll.asp?studioid=25709&tg=29&vt=&lvl=&stype=-101&view=day&trn=0&page=&catid=&prodid=&date=4%2f20%2f2017&classid=0&prodGroupId=&sSU=&optForwardingLink=&qParam=&justloggedin=&nLgIn=&pMode=0&loc=1',
        program_type: 'Arts',
        program_description: "This camp requires a week session enrollment for campers. We will focus on growing as artists. We'll focus on fundamental skills such as light and shadow, color mixing using the color wheel, 1-point & 2-point perspective drawings, and other building blocks for making successful artwork.",
        participant_gender: 'Any',
        participant_age_min: 3,
        participant_age_max: 12,
        program_start_date: '2018-07-31',
        program_end_date: '2018-08-04',
        program_start_time: '9:00AM',
        program_end_time: '4:00PM',
        overnight: 'False',
        full_day: 'True',
        part_day: 'True',
        cost: 199
      }, {
        id: 24,
        organization_name: 'American Dance Training Camps',
        program_name: 'The ULTIMATE CO Dance Camp',
        program_address: '81699 US-40',
        program_city: 'Winter Park',
        program_state: 'CO',
        zipcode: 80482,
        program_phone: '(866)383-2382',
        program_website: 'http://www.americandancetrainingcamp.com/locations/co-dance-camp/',
        program_type: 'Arts',
        program_description: "At ADTC in CO, you'll take 4-5 dance classes per-day, Mon through Fri. Classes are taught by our professional choreographers. The core dance disciplines you'll take are contemporary, hip hop and jazz (styles vary and may include Bwy or lyrical). Elective dance classes include ballet, tap & world dance. No matter what your dance level or background, our curriculum is designed to challenge you. You'll be organized into groups by age & ability and get to perform in a big Friday Show.",
        participant_gender: 'Any',
        participant_age_min: 8,
        participant_age_max: 17,
        program_start_date: '2018-06-18',
        program_end_date: '2018-07-01',
        program_start_time: '8:00AM',
        program_end_time: '6:00PM',
        overnight: 'True',
        full_day: 'True',
        part_day: 'False',
        cost: 1498
      }, {
        id: 25,
        organization_name: 'Apex Park and Recreation District',
        program_name: 'Boredom Busters',
        program_address: '13150 W. 72nd Ave.',
        program_city: 'Arvada',
        program_state: 'CO',
        zipcode: 80005,
        program_phone: '(303)431-9600',
        program_website: 'http://apexprd.org/activities/camps',
        program_type: 'Sports',
        program_description: "Your kids can enjoy all their favorite games, plus swimming and rock climbing. Ages 5-7 start in the gym on Tuesdays and Thursdays with games like kickball and Sharks & Minnows. Afterwards, they'll go rock climbing on Tuesdays and swimming on Thursdays. Ages 8-11 start in the gym on Tuesdays and Thursdays with games. Afterwards, they'll go swimming on Tuesdays and go rock climbing on Thursdays. A swim shirt must be purchased and worn to each class. Parents-you can stay and work out during the program, or drop off your child and pick them up at 10 am. Be sure your child wears a swimsuit under their clothing on their swim day and closed-toe shoes for rock climbing days. For more information or to sign up, visit Guest Services.",
        participant_gender: 'Any',
        participant_age_min: 5,
        participant_age_max: 11,
        program_start_date: '2018-05-30',
        program_end_date: '2018-08-10',
        program_start_time: '8:30AM',
        program_end_time: '10:00AM',
        overnight: 'False',
        full_day: 'False',
        part_day: 'True',
        cost: 49
      }, {
        id: 26,
        organization_name: 'Apex Park and Recreation District',
        program_name: 'CIT Day Camp',
        program_address: '6820 W. 66th Ave.',
        program_city: 'Arvada',
        program_state: 'CO',
        zipcode: 80003,
        program_phone: '(303)403-2555',
        program_website: 'http://apexprd.org/activities/camps',
        program_type: 'Education',
        program_description: 'The CIT (Counselor In Training) program is designed for teens (13-15) who enjoy working with younger kids and who are interested in learning job/life skills. Goals: Encouraging youth collaboration, experiencing other perspectives, collective planning and implementation of activities, and having fun! Developing youth leadership through social awareness and volunteerism, planning and implementing fundraising activities, working daily with younger campers, demonstrating responsibility for self and others, and confidence building opportunities.',
        participant_gender: 'Any',
        participant_age_min: 13,
        participant_age_max: 15,
        program_start_date: '2018-06-06',
        program_end_date: '2018-07-28',
        program_start_time: '8:00AM',
        program_end_time: '5:00PM',
        overnight: 'False',
        full_day: 'True',
        part_day: 'False',
        cost: 120
      }, {
        id: 27,
        organization_name: 'Apex Park and Recreation District',
        program_name: 'Little Athletes',
        program_address: '5724 OAK STREET',
        program_city: 'Arvada',
        program_state: 'CO',
        zipcode: 80002,
        program_phone: '(303)431-9600',
        program_website: 'http://apexprd.org/activities/camps',
        program_type: 'Sports',
        program_description: "A multi-sports clinic for ages 3-6, to improve agility and coordination through a new sport each week. They'll learn football, kick ball, and baseball skills and practice field events like softball toss, modified long jump, shoe kick and more. Work on sack and 3-legged races, 20-yard dash, obstacle courses and relays. Perform all skills learned at the Field Day, held during the last class. NOTE: Some classes may be held outdoors.",
        participant_gender: 'Any',
        participant_age_min: 3,
        participant_age_max: 6,
        program_start_date: '2018-06-05',
        program_end_date: '2018-09-01',
        program_start_time: '9:00AM',
        program_end_time: '10:45AM',
        overnight: 'False',
        full_day: 'False',
        part_day: 'True',
        cost: 60
      }, {
        id: 28,
        organization_name: 'Apex Park and Recreation District',
        program_name: 'Skateboard Summer Full Day Camp',
        program_address: 'Arvada Skate Park',
        program_city: 'Arvada',
        program_state: 'CO',
        zipcode: 80004,
        program_phone: '(303)431-9600',
        program_website: 'http://apexprd.org/activities/camps',
        program_type: 'Sports',
        program_description: "Learn how to be safe and have fun on your skateboard while riding some of the best parks in the Front Range. We skate our 'home park' in the morning before jumping on our Skate Bus to check out different parks in the area, explore a variety of terrain and visit multiple skater-owned skate shops. Explore all areas of street and skatepark riding, from safety and etiquette to advanced park riding. We will also go swimming once a week. Come make new friends, have fun, and be a part of our active skateboard community. Please bring a skateboard, helmet (other pads recommended), a healthy lunch, water bottle, sunscreen and some good energy.",
        participant_gender: 'Any',
        participant_age_min: 5,
        participant_age_max: 15,
        program_start_date: '2018-06-05',
        program_end_date: '2018-08-18',
        program_start_time: '8:30AM',
        program_end_time: '3:30PM',
        overnight: 'False',
        full_day: 'True',
        part_day: 'False',
        cost: 345
      }, {
        id: 29,
        organization_name: 'Apex Park and Recreation District',
        program_name: 'Taekwon-Do',
        program_address: '6820 W. 66th Ave.',
        program_city: 'Arvada',
        program_state: 'CO',
        zipcode: 80003,
        program_phone: '(303)431-9600',
        program_website: 'http://apexprd.org/activities/camps',
        program_type: 'Sports',
        program_description: 'Meets Saturday morning from 9 to 10:30 am. Students may also attend the Wednesday family class if they have an older family member training in the regular 8 to adult class. Students may attend all classes listed that are appropriate to their age or family situation. Class instruction, color belt testing fees and annual federation membership are covered in the registration fee.',
        participant_gender: 'Any',
        participant_age_min: 8,
        participant_age_max: 18,
        program_start_date: '2018-06-03',
        program_end_date: '2018-09-28',
        program_start_time: '6:00PM',
        program_end_time: '9:00PM',
        overnight: 'False',
        full_day: 'False',
        part_day: 'True',
        cost: 120
      }, {
        id: 30,
        organization_name: 'Apex Park and Recreation District',
        program_name: 'Youth Sports Camp',
        program_address: '11706 W. 82nd ave.',
        program_city: 'Arvada',
        program_state: 'CO',
        zipcode: 80004,
        program_phone: '(303)431-9600',
        program_website: 'http://apexprd.org/activities/camps',
        program_type: 'Sports',
        program_description: 'Spend your summer exploring new sports and getting in shape! Camps are divided by ages for an overall quality experience. Coaches help players improve tactical awareness in each sport. Bring a snack and water bottle. The multi-sport camp starts at the Apex Simms Street Center, then goes to different outdoor locations each day.',
        participant_gender: 'Any',
        participant_age_min: 5,
        participant_age_max: 14,
        program_start_date: '2018-07-10',
        program_end_date: '2018-07-21',
        program_start_time: '9:00AM',
        program_end_time: '3:30PM',
        overnight: 'False',
        full_day: 'False',
        part_day: 'True',
        cost: 100
      }];
      return knex('camp').insert(camps);
    });
};
